name: Devsecops End to End Pipeline

on:
  push:
   branches: ["main"]
  workflow_dispatch:

jobs:
# CI [ Continuous Integration with Security Scanning]
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pipeline triggered"

  code-quality:
    uses: ./.github/workflows/code-quality.yml
  

  secrets-scan:
    needs: code-quality
    uses: ./.github/workflows/secrets-scan.yml
    secrets: inherit

  dependency-scan:
    needs: secrets-scan
    uses: ./.github/workflows/dependancy-check.yml
    

  docker-scan:
    needs: dependency-scan
    uses: ./.github/workflows/docker-lint.yml
    secrets: inherit
  
  build:
    needs: [code-quality, secrets-scan, dependancy-scan, docker-scan]
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit