name: Devsecops End to End Pipeline

on:
  workflow_dispatch:

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  

  secrets-scan:
    needs: code-quality
    uses: ./.github/workflows/secrets-scan.yml
    

  dependency-scan:
    needs: secrets-scan
    uses: ./.github/workflows/dependancy-check.yml
    

  docker-scan:
    needs: dependency-scan
    uses: ./.github/workflows/docker-lint.yml
    