---
name: Hello
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
      - name: say hello to username
        run: echo "Hello $USER"
  learn:
   runs-on: ubuntu-latest
   steps:
    - name: what are you leaning?
      run: echo "learning Devops from TWS"
  phases:
   runs-on: ubuntu-latest
   steps:
     - name: What is the progress!!
       run: echo "Finished Phase1 from TWS"
       
    
