name: Secrets Scan
on:
 workflow_call

jobs:
    Secrets-Scan:
        runs-on: ubuntu:latest
        steps:
             - name: checkout code
               uses: actions/checkout@v4
             - name: run git leaks scanner
               uses: gitleaks/gitleaks-action@v2
              